version: '3'
services:
  mkdir:
    image: alpine
    volumes:
    - ./certs:/certs
    command: sh -c "mkdir -p /certs/${ROOT_DIR}; mkdir -p /certs/${DOMAIN}"

  ca:
    build:
      context: .
      dockerfile: ./Docker/omgwtfssl/Dockerfile
    container_name: ${CA_NAME}
    depends_on:
    - mkdir
    volumes:
    - ./certs:/certs
    environment:
    - CA_SUBJECT=${CA_NAME}
    - SSL_SUBJECT=${DOMAIN}
    - SSL_DNS=${ALT_DOMAINS}
    - SSL_IP=${IPS}
    - CA_KEY=${ROOT_DIR}/ca-key.pem
    - CA_CERT=${ROOT_DIR}/ca.pem
    - SSL_KEY=${DOMAIN}/key.pem
    - SSL_CERT=${DOMAIN}/cert.pem
    - SSL_CSR=${DOMAIN}/key.csr
    - CA_EXPIRE=${CA_EXPIRE}
    - SSL_EXPIRE=${SSL_EXPIRE}
    - SSL_SIZE=${SSL_SIZE}

  nginx:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
    ports:
    - 443:443
    volumes:
    - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    - ./certs/${DOMAIN}:/etc/nginx/conf.d/ssl # https化
    tty: true
    depends_on:
      ca:
        condition: service_completed_successfully
